### ISSUE TITLE
spie sprint

### ISSUE THREAD

**Issue by massich** [I2Cvb/prostate#4]
# This Issue will be used document and drive the experimentation discussed in **SPIE**
## Description

A dirty implementation of our prostate methods using deep learining. The volumes would be sliced (as sub volume) in a sliding manner and a decision (cancer / non-cancer) would be made for each subvolume.
## Tasks
- [ ] basic caffe knowledge
- [ ] Initial caffe integration
  - [ ] Segment only the _midle_ slice of the volume
  - [ ] volume slicing
## Extra- things to try
- [ ] Incorporate a position prior. Maybe you can have T1, DCE, ADC (+ a modality position or atlas) _see issue #5_
  - [ ] use Atlas Prior 
  - [ ] use position image [X, Y, Z] of size (MxNxRx3) where the central pixel has a 0,0,0

**Comment by massich** [comment]
@glemaitre I think this is what we need https://github.com/BVLC/caffe/wiki/Model-Zoo#fcn

**Comment by massich** [comment]
https://www.youtube.com/watch?v=rvMVqPsXL10 @ min 40, injecting rgb images + depth, either at the first level of the network (or more fancy, inject one of the images at some deeper layer within the network). We can use this to inject the DCE and the ADC at its corresponding resolution
